### ISSUE TITLE
1/19 - 1/ 21 Ch2-5 문제 풀이

### ISSUE THREAD

**Issue by miunseol** [miunseol/Java-Practice#1]
연습문제 pdf파일

[java_jungsuk3_연습문제_20160318.pdf](https://github.com/miunseol/Java-Practice/files/13983908/java_jungsuk3_._20160318.pdf)

Ch2~Ch4를 푼 코드 파일들을 압축하여 올리면 될 것 같아요

![Image](https://github.com/miunseol/Java-Practice/assets/133627851/fde67154-dfe8-4e6b-b95e-6cc5cfdec4f3)

**Comment by miunseol** [comment]
Chapter 2 과제
1,3,5,6,7,9,11,13
Chapter 3 과제
1,2,3,4,5,6,7
Chapter 4 과제
2,3,4,5,6,8,9,13

**Comment by miunseol** [comment]
[example.zip](https://github.com/miunseol/Java-Practice/files/13986747/example.zip)

**Comment by kikihong** [comment]
[java31.zip](https://github.com/miunseol/Java-Practice/files/14003221/java31.zip)
